version: "2"
checks:
  # Disable checks for similar code.
  # Because this creates too many false positives.
  similar-code:
    enabled: false
  # Increase the number of lines allowed for a method.
  # Because this is more reasonable for JavaScript.
  method-lines:
    config:
      threshold: 50
exclude_patterns:
# Limited the number of patterns compared to backend
# One notable pattern the backend excludes is "__tests__", meaning codeclimate isn't judging backend tests
# Should we include that restriction for our tests?
  - 'public/'
  - '**/node_modules/'