version: "2"
checks: 
  similar-code: 
    enabled: false
  identical-code:
    enabled: true
    config:
      threshold: 100
    method-lines:
      enabled: true
      config: 
        threshold: 65


exclude_patterns: 
  --"**/_test_/"
  --"tests/"
  --"components/"

  
